### PR TITLE
Populated missing sqale data for C# rules.

### PR DESCRIPTION
**Pull request by pwillworth**
Requesting to merge in the addition of Sqale data to the original file setup before I split the vbnet data to separate file and remove unapplicable rules.

### CODE REVIEW

**Comment by ganncamp** [comment]
Merged. Thanks @pwillworth

**Comment by pwillworth** [comment]
Cool!  Last pull request from me on this is submitted.

**Comment by ganncamp** [comment]
@pwillworth to enter the ticket to incorporate your changes, I need to know about compatibility. You mentioned that you were planning to update the list of rules. What R# versions is this new model compatible with and/or with which versions is it incompatible?

**Comment by pwillworth** [comment]
The updating of the rules I did was actually a sync between this sqale data file and current list of rules available in the 1.0 version of the sonar-resharper plugin.  I was not updating it based on some new resharper version.  I do not know what version of Resharper the sonar-resharper plugin is based on.

**Comment by ganncamp** [comment]
Thanks @pwillworth. That helps to know. Somehow I'd gotten the wrong impression.

**Comment by pwillworth** [comment]
I was using the latest version of resharper (9) when doing the analysis on each rule to determine what language it was for and the category/time.  During that, I noticed very few discrepancies between what was in the Sonarqube resharper plugin and Resharper.  So I'm guessing the Resharper version the plugin is based on is very recent.

When I first started working on this, I noticed a lot of differences between the sqale model file rules list in this repo and the export I got out of the plugin, so I shifted gears and worked on updating the list of rules for this sqale file first, which resulted in my first pull request.

**Comment by ganncamp** [comment]
Thanks Paul. That makes sense. 
So you know, it could be a while before the .NET team cycles back around to release this. :-(

**Pull request merged**
