### PR TITLE
Update to most current Resharper plugin ruleset

### PR DESCRIPTION
**Pull request by pwillworth**
Using an export of the latest full list of rules from the Resharper plugin and a utility script I wrote, I updated this model to remove rules no longer in the plugin and add rules that are in the plugin but were not present in the model.

### CODE REVIEW

**Comment by ganncamp** [comment]
Sorry I didn't notice this sooner @pwillworth. Thanks for your contribution!

**Comment by pwillworth** [comment]
No worries!  Will be sending more your way before long to populate some of the missing data.

**Comment by ganncamp** [comment]
Great news @pwillworth !
So you know, they won't be updating the main list of rules in this next release of the plugin, but as soon as they do, your work will show up.
In case you're curious, [this](https://github.com/SonarCommunity/sonar-resharper/blob/master/src/main/resources/org/sonar/plugins/resharper/rules.xml) is the file that controls the list of rules in the plugin.

**Comment by pwillworth** [comment]
Ah, that's good to know, thanks.  It also makes me think of something.  Resharper has a number of rules that are specific only to languages that the Sonar Resharper plugin ignores because there are other plugins that handle them (Web/HTML, Javascript, ASP, VB.NET).  I'm tempted to delete these from the Resharper plugin rules list.  Is that a good idea or not?

**Comment by ganncamp** [comment]
I'll defer that to @dbolkensteyn

**Comment by dbolkensteyn** [comment]
:+1: and there already is a ticket to do so: http://jira.sonarsource.com/browse/SONARRSHPR-3

**Comment by pwillworth** [comment]
Cool, I'll plan on removing non C# rules from this model except VB ones which I'll move to a separate file to match plans for the plugin resource.

**Comment by pwillworth** [comment]
I have submitted a new pull request to populate SQALE values to this file.  I also have completed work to split the non C# rules from this file and will submit as another pull request after the values one is merged.

**Pull request merged**
